### ISSUE TITLE
match gets rid of unsaved changes

### ISSUE THREAD

**Issue by SwartzCr** [hercules-team/python-augeas#15] opened 2016-01-22 20:05 UTC
I'm working on Let's Encrypt and ran into a bug where if a directive is added to a file but not saved, and then match is called augeas forgets about the change.
see https://github.com/letsencrypt/letsencrypt/issues/2228#issuecomment-173724343 for my tale of woe

I assume this is not the intended result of calling match, as running the same command from augtool doesn't result in the same loss of directive change.

**Comment by thedrow** [comment] 2017-08-29 10:46
Any chance you'll provide a test that demonstrates this issue?
The problem is definitely somewhere in augeas itself.
The python bindings call match directly.

**Comment by SwartzCr** [comment] 2017-08-31 15:52
I'd be happy to try - please remind me next week if I haven't given you an example by then

**Comment by thedrow** [comment] 2017-09-04 13:38
@SwartzCr Ping :)

**Comment by lutter** [comment] 2017-09-08 19:46
I would also be very interested in seeing a reproducer for this. If augeas loses an unsaved change, that should only happen if (1) the whole augeas instance gets recreated, (2) aug_load is called (which will replace your tree with whatever is on disk) or (3) aug_rm is called on those new items. aug_match does not modify the tree in any way.

There's of course always the possibility that there is a bug somewhere ...

**Comment by SwartzCr** [comment] 2017-09-08 22:27
I'm trying to reproduce, but unfortunately I've forgotten most of my augeas-fu
Would one of you be willing to spend some time with me on irc to help me use the proper augeas commands?

**Comment by lutter** [comment] 2017-09-09 01:28
@SwartzCr yes, totally, though my availability might be a bit spotty - ping me next week on IRC when you have time and we'll try and work something out. Even just a short Python program that shows the issue would be enough.

**Comment by joohoi** [comment] 2017-10-03 19:42
I dug a bit into this, and in the original story the method `_get_include_path()` had a `aug.load()` lurking in there under the hood in certain cases, and I strongly believe that it was the underlying issue after all. (see: https://github.com/certbot/certbot/issues/2265#issuecomment-332508010 )

@SwartzCr is unavailable for a while now, but hopefully can confirm this later on.

**Comment by lutter** [comment] 2017-10-04 03:30
@joohoi cool .. thanks for clearing that up, and an errant aug.load does explain this issue.

**Comment by lutter** [comment] 2017-11-11 00:20
Closing as it seems this wasn't the issue. Please reopen if that's not the case.

**Closed by lutter** 2017-11-11 00:20 UTC

**Comment by SwartzCr** [comment] 2017-11-13 21:59
That sounds plausible, also I tried to go about re-creating and reproducing the issue a while ago, but found that the code base had moved enough in my time away that I had a hard time convincing myself that the issue still existed. So I'm happy to leave this a accurately closed.
